//! # Verifier
//!
//! This crate contains utilities for verifying SP1 Groth16 proofs on Solana.
//!
//! # Example
//! ```no_run
//! use sp1_sdk::proof::SP1ProofWithPublicValues;
//! use sp1_solana::{verify_proof, GROTH16_VK_6_1_0_BYTES};
//!
//! // Load the sp1_proof_with_public_values from a file.
//! let sp1_proof_with_public_values_file = "../proofs/fibonacci_proof.bin";
//! let sp1_proof_with_public_values =
//!     SP1ProofWithPublicValues::load(&sp1_proof_with_public_values_file).unwrap();
//!
//! // Fetch the proof and public inputs from the SP1ProofWithPublicValues.
//! let proof_bytes = sp1_proof_with_public_values.bytes();
//! let sp1_public_inputs = sp1_proof_with_public_values.public_values.to_vec();
//!
//! // Typically, the vkey hash is computed from `vk.bytes32()` on the SP1 program's vkey.
//! let vkey_hash = "0x009986cfea64a21abe25e985b2b2392d2fd0a6f1a144a04e78bf6b61d1f972fd";
//!
//! verify_proof(&proof_bytes, &sp1_public_inputs, &vkey_hash, GROTH16_VK_6_1_0_BYTES).unwrap();
//! ```

use groth16_solana::groth16::Groth16Verifyingkey;
use sha2::{Digest, Sha256};

#[cfg(test)]
mod test;

mod utils;
use utils::*;

/// Groth16 verification keys for different SP1 versions.
pub const GROTH16_VK_6_1_0_BYTES: &[u8] = include_bytes!("../vk/v6.1.0/groth16_vk.bin");
pub const GROTH16_VK_5_0_0_BYTES: &[u8] = include_bytes!("../vk/v5.0.0/groth16_vk.bin");
pub const GROTH16_VK_4_0_0_RC3_BYTES: &[u8] = include_bytes!("../vk/v4.0.0-rc.3/groth16_vk.bin");
pub const GROTH16_VK_3_0_0_BYTES: &[u8] = include_bytes!("../vk/v3.0.0/groth16_vk.bin");
pub const GROTH16_VK_3_0_0_RC4_BYTES: &[u8] = include_bytes!("../vk/v3.0.0rc4/groth16_vk.bin");
pub const GROTH16_VK_2_0_0_BYTES: &[u8] = include_bytes!("../vk/v2.0.0/groth16_vk.bin");

/// VK root for SP1 circuit v6.1.0, embedded in Groth16 proof headers.
/// This is tied to `SP1_CIRCUIT_VERSION`; SDK v6.1.0 through v6.3.1 use this same circuit.
pub const VK_ROOT_6_1_0_BYTES: [u8; 32] =
    hex_literal::hex!("002f850ee998974d6cc00e50cd0814b098c05bfade466d28573240d057f25352");

/// Verifies a proof using raw bytes, without any checks.
///
/// The public inputs are the five SP1 6.1 Groth16 field elements.
/// The proof is a decompressed G1 element, followed by a decompressed G2 element, followed by a
/// decompressed G1 element.
pub fn verify_proof_raw<const N: usize>(
    proof: &[u8],
    public_inputs: &[[u8; 32]; N],
    vk: &[u8],
) -> Result<(), Error> {
    let proof = load_proof_from_bytes(proof)?;
    let vk = load_groth16_verifying_key_from_bytes(vk)?;
    let public_inputs = load_public_inputs(public_inputs);

    let vk = Groth16Verifyingkey {
        nr_pubinputs: vk.nr_pubinputs as usize,
        vk_alpha_g1: vk.vk_alpha_g1,
        vk_beta_g2: vk.vk_beta_g2,
        vk_gamme_g2: vk.vk_gamma_g2,
        vk_delta_g2: vk.vk_delta_g2,
        vk_ic: vk.vk_ic.as_slice(),
    };

    let mut verifier = groth16_solana::groth16::Groth16Verifier::new(
        &proof.pi_a,
        &proof.pi_b,
        &proof.pi_c,
        &public_inputs.inputs,
        &vk,
    )
    .map_err(|_| Error::VerificationError)?;

    verifier.verify().map_err(|_| Error::VerificationError)
}

/// Verifies a proof generated by [`SP1ProofWithPublicValues`].
///
/// The proof is expected to be from this method on `SP1ProofWithPublicValues`:
/// https://docs.rs/sp1-sdk/latest/sp1_sdk/proof/struct.SP1ProofWithPublicValues.html#method.bytes
/// The public inputs are directly taken from the `SP1PublicValues`.
/// https://docs.rs/sp1-sdk/latest/sp1_sdk/struct.SP1PublicValues.html#method.as_slice
/// The vkey hash is derived from running `vk.bytes32()` on the program's vkey.
/// https://docs.rs/sp1-sdk/latest/sp1_sdk/trait.HashableKey.html#method.bytes32
#[inline]
pub fn verify_proof(
    proof: &[u8],
    sp1_public_inputs: &[u8],
    sp1_vkey_hash: &str,
    groth16_vk: &[u8],
) -> Result<(), Error> {
    if proof.len() < SP1_GROTH16_HEADER_LENGTH + GROTH16_PROOF_LENGTH {
        return Err(Error::InvalidData);
    }

    // Hash the vk and get the first 4 bytes.
    let groth16_vk_hash: [u8; 4] = Sha256::digest(groth16_vk)[..4].try_into().unwrap();

    // Check to make sure that this proof was generated by the groth16 proving key corresponding to
    // the given groth16_vk.
    //
    // SP1 prepends the raw Groth16 proof with the first 4 bytes of the groth16 vkey to
    // facilitate this check.
    if groth16_vk_hash != proof[..4] {
        return Err(Error::Groth16VkeyHashMismatch);
    }

    let sp1_vkey_hash = decode_sp1_vkey_hash(sp1_vkey_hash)?;
    let exit_code: [u8; 32] = proof[4..36].try_into().map_err(|_| Error::InvalidData)?;
    let vk_root: [u8; 32] = proof[36..68].try_into().map_err(|_| Error::InvalidData)?;
    let proof_nonce: [u8; 32] = proof[68..100].try_into().map_err(|_| Error::InvalidData)?;

    if vk_root != VK_ROOT_6_1_0_BYTES {
        return Err(Error::VkeyRootMismatch);
    }

    if exit_code != [0u8; 32] {
        return Err(Error::ExitCodeMismatch);
    }

    let raw_proof = &proof[SP1_GROTH16_HEADER_LENGTH..];
    let public_values = groth16_public_values(
        sp1_vkey_hash,
        sp1_public_inputs,
        exit_code,
        vk_root,
        proof_nonce,
    );
    if verify_proof_raw(raw_proof, &public_values, groth16_vk).is_ok() {
        return Ok(());
    }

    // SP1 proofs may hash public values with SHA-256 or Blake3.
    // Try SHA-256 first; a cross-hash collision is infeasible.
    let public_values = groth16_public_values_blake3(
        sp1_vkey_hash,
        sp1_public_inputs,
        exit_code,
        vk_root,
        proof_nonce,
    );
    verify_proof_raw(raw_proof, &public_values, groth16_vk)
}
