[workspace]
members = ["verifier", "example/script", "example/solana/program"]
resolver = "2"

[workspace.dependencies]
borsh = "1.5.1"
solana-program = { git = "https://github.com/anza-xyz/agave" }
bincode = "1.3.3"
eyre = "0.6.1"
groth16-solana = { path = "verifier" }
