[package]
name = "groth16-verifier"
version = "0.1.0"
edition = "2021"
authors = ["Bhargav Annem"]
description = "A Groth16 verifier implementation"
license = "MIT OR Apache-2.0"
repository = "https://github.com/0xWOLAND/groth16-verifier"
readme = "README.md"
keywords = ["cryptography", "zero-knowledge", "groth16", "verifier"]
categories = ["cryptography"]

[dependencies]
bn = { git = "https://github.com/sp1-patches/bn", branch = "bhargav/gnark-bn254-verifier", package = "substrate-bn" }
thiserror = "1.0.63"
